name: 'churn'
version: '1.0.0'
config-version: 2
profile: 'churn'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  churn:
    staging:
      +materialized: table
      +schema: staging
    features:
      +materialized: table
      +schema: features
